Script updates

diff --git a/scripts/get b/scripts/get
--- a/scripts/get
+++ b/scripts/get
@@ -14,6 +14,10 @@ function print_dn {
 host="$1"
 certificate="$certs_home/$host/$host.crt"
 
+if [ ! -f "$certificate" ]; then
+    echo "Certificate not found."
+    exit 1
+fi
 
 # Return the encoded certificate
 echo "================================"
